import test from 'node:test';
import assert from 'node:assert/strict';
import {validateIntake,receiptBody,handoverBody} from '../supabase/functions/charter-bridge/core.js';
const valid={enquiry_reference:'PCO-TEST-VALIDATION-20260916',area:'France',dates:'July 2027',guests:'8 adults',budget:'£100k–£250k',budget_scope:'Charter fee only',name:'Test',email:'privatecharteroffice@gmail.com',sharing_permission:'accepted',service_acknowledgement:'accepted'};
test('records only permitted fields and server consent version',()=>{const {payload}=validateIntake({...valid,consent_version:'fake',is_test:true,status:'sent'});assert.equal(payload.consent_version,'2026-09-16');assert.equal(payload.is_test,undefined);assert.equal(payload.status,undefined);});
test('requires service acknowledgement and complete brief',()=>{assert.throws(()=>validateIntake({...valid,service_acknowledgement:''}),/SERVICE_ACKNOWLEDGEMENT/);assert.throws(()=>validateIntake({...valid,budget_scope:''}),/MISSING_REQUIREMENTS/);});
test('rejects header injection, oversized priorities and malformed references',()=>{assert.throws(()=>validateIntake({...valid,email:'me@example.com\nBcc: other@example.com'}),/INVALID_EMAIL/);assert.throws(()=>validateIntake({...valid,requirements:'x'.repeat(4001)}),/INVALID_FIELD/);assert.throws(()=>validateIntake({...valid,enquiry_reference:'../customer'}),/INVALID_REFERENCE/);});
test('absence of sharing permission never becomes permission',()=>{const {payload}=validateIntake({...valid,sharing_permission:undefined});assert.equal(payload.sharing_permission,'not_given');assert.match(receiptBody(valid.enquiry_reference,payload),/before sharing/);});
test('handover includes budget basis, contact and explicit receipt link',()=>{const {payload}=validateIntake(valid);const body=handoverBody(valid.enquiry_reference,payload,'Rehearsal','https://example.com/receipt');assert.match(body,/Budget basis: Charter fee only/);assert.match(body,/privatecharteroffice@gmail.com/);assert.match(body,/https:\/\/example.com\/receipt/);assert.match(body,/does not confirm availability/);});
